#!/usr/bin/env bash
set -euo pipefail

# Builds Odin and creates a stay-open Dock app that supervises the production
# server without registering a login item.

REPO="$(cd "$(dirname "$0")/.." && pwd)"
SERVER="${REPO}/server/dist/index.js"
PORT="${HELM_PORT:-7420}"
APP="/Applications/Odin.app"
APP_MARKER="odin-local-launcher-v1"
STATE_DIR="${HOME}/Library/Application Support/Odin"
LOG_DIR="${HOME}/Library/Logs/Odin"

case "${PORT}" in
  ''|*[!0-9]*)
    echo "HELM_PORT must be a number from 1 to 65535." >&2
    exit 1
    ;;
esac
while [[ "${PORT}" == 0* && ${#PORT} -gt 1 ]]; do
  PORT="${PORT#0}"
done
if (( ${#PORT} > 5 )) || (( PORT < 1 || PORT > 65535 )); then
  echo "HELM_PORT must be a number from 1 to 65535." >&2
  exit 1
fi

resolve_executable() {
  local executable
  executable="$(command -v "$1" 2>/dev/null || true)"
  if [[ "${executable}" != /* || ! -x "${executable}" ]]; then
    echo "Required executable not found: $1" >&2
    exit 1
  fi
  printf '%s\n' "${executable}"
}

resolve_optional_executable() {
  local executable
  executable="$(command -v "$1" 2>/dev/null || true)"
  if [[ "${executable}" == /* && -x "${executable}" ]]; then
    printf '%s\n' "${executable}"
  fi
}

# Finder apps do not inherit an interactive shell's PATH. Capture every
# non-shell executable used by the app while the installer has the user's PATH.
NODE="$(resolve_executable node)"
NODE_MAJOR="$("${NODE}" -p 'process.versions.node.split(".")[0]')"
NODE_MINOR="$("${NODE}" -p 'process.versions.node.split(".")[1]')"
if (( NODE_MAJOR < 20 || (NODE_MAJOR == 20 && NODE_MINOR < 19) || NODE_MAJOR == 21 || (NODE_MAJOR == 22 && NODE_MINOR < 12) || NODE_MAJOR == 23 )); then
  echo "Odin requires Node.js 20.19+, 22.12+, or 24+; Node.js 21 and 23 are unsupported (found $("${NODE}" --version))." >&2
  exit 1
fi
NPM="$(resolve_executable npm)"
CURL="$(resolve_executable curl)"
LSOF="$(resolve_executable lsof)"
NOHUP="$(resolve_executable nohup)"
PS="$(resolve_executable ps)"
OSACOMPILE="$(resolve_executable osacompile)"
CODESIGN="$(resolve_executable codesign)"
CLAUDE="$(resolve_optional_executable claude)"
TMP=""
BACKUP_APP=""

cleanup() {
  [[ -z "${TMP}" || ! -d "${TMP}" ]] || /bin/rm -rf "${TMP}"
  if [[ -n "${BACKUP_APP}" && -d "${BACKUP_APP}" && ! -e "${APP}" && ! -L "${APP}" ]]; then
    /bin/mv "${BACKUP_APP}" "${APP}"
  fi
}
trap cleanup EXIT

is_odin_app_bundle() {
  local bundle="$1"
  local marker="${bundle}/Contents/Resources/odin-app.marker"
  local helper="${bundle}/Contents/Resources/odin-launcher.sh"
  local value=""
  [[ -d "${bundle}" && ! -L "${bundle}" ]] || return 1
  if [[ -r "${marker}" ]]; then
    IFS= read -r value < "${marker}" || return 1
    [[ "${value}" == "${APP_MARKER}" ]]
    return
  fi
  # Recognize the launcher generated by earlier Odin versions for one safe upgrade.
  [[ -x "${helper}" ]] && /usr/bin/grep -Fq 'ODIN_LAUNCHER_INSTANCE' "${helper}"
}

stop_existing_installation() {
  local helper="${APP}/Contents/Resources/odin-launcher.sh"
  local pid command i
  local node_name="${NODE##*/}"

  if [[ ( -e "${APP}" || -L "${APP}" ) ]] && ! is_odin_app_bundle "${APP}"; then
    echo "${APP} exists but is not an Odin installation; nothing was changed." >&2
    exit 1
  fi

  # Move the validated bundle immediately, then validate what was moved. This
  # prevents a path replacement between ownership validation and removal.
  if [[ -d "${APP}" ]]; then
    BACKUP_APP="${APP}.installing.$$"
    /bin/mv "${APP}" "${BACKUP_APP}"
    if ! is_odin_app_bundle "${BACKUP_APP}"; then
      [[ -e "${APP}" || -L "${APP}" ]] || /bin/mv "${BACKUP_APP}" "${APP}"
      BACKUP_APP=""
      echo "The application changed while installation was starting; nothing was removed." >&2
      exit 1
    fi
    helper="${BACKUP_APP}/Contents/Resources/odin-launcher.sh"
  fi

  # Stop the supervisor first so its idle handler cannot restart the server.
  while read -r pid command; do
    [[ "${pid}" =~ ^[0-9]+$ ]] || continue
    if [[ "${command}" == "${APP}/Contents/MacOS/applet"* ]]; then
      command="$("${PS}" -ww -p "${pid}" -o command= 2>/dev/null || true)"
      [[ "${command}" == "${APP}/Contents/MacOS/applet"* ]] || continue
      kill -TERM "${pid}" 2>/dev/null || true
      for i in {1..30}; do
        kill -0 "${pid}" 2>/dev/null || break
        /bin/sleep 0.1
      done
      command="$("${PS}" -ww -p "${pid}" -o command= 2>/dev/null || true)"
      if [[ "${command}" == "${APP}/Contents/MacOS/applet"* ]]; then
        kill -KILL "${pid}" 2>/dev/null || true
      fi
    fi
  done < <("${PS}" -axo pid=,command=)

  # Then let the previous launcher drain only the server it owns.
  if [[ -x "${helper}" ]]; then
    if ! /bin/bash "${helper}" stop >/dev/null 2>&1; then
      echo "The existing Odin launcher is busy or damaged; installation was not changed." >&2
      exit 1
    fi
  fi

  local health=""
  health="$("${CURL}" --fail --silent --connect-timeout 1 --max-time 1 \
    "http://127.0.0.1:${PORT}/api/health" 2>/dev/null || true)"
  if [[ -n "${health}" ]] && "${NODE}" -e '
    try {
      const health = JSON.parse(process.argv[1]);
      process.exit(health.service === "odin" && health.checkoutRoot === process.argv[2] ? 0 : 1);
    } catch { process.exit(1); }
  ' "${health}" "${REPO}"; then
    echo "A manually started Odin server is still running on port ${PORT}. Stop it before reinstalling." >&2
    exit 1
  fi

  # Never terminate a manually started production server. Refuse the upgrade
  # rather than mixing a process running old code with freshly built assets.
  while read -r pid command; do
    [[ "${pid}" =~ ^[0-9]+$ ]] || continue
    if [[ "${command}" == "${NODE} ${SERVER}"* || "${command}" == "${node_name} ${SERVER}"* || "${command}" == *" ${SERVER}"* ]]; then
      echo "A manually started Odin production server is still running (PID ${pid}). Stop it before reinstalling." >&2
      exit 1
    fi
    if [[ "${command}" == "${node_name} dist/index.js"* ]]; then
      local cwd_info
      cwd_info="$("${LSOF}" -a -p "${pid}" -d cwd -Fn 2>/dev/null || true)"
      if [[ "${cwd_info}" == *$'\n'"n${REPO}/server"* ]]; then
        echo "A manually started Odin production server is still running (PID ${pid}). Stop it before reinstalling." >&2
        exit 1
      fi
    fi
  done < <("${PS}" -axo pid=,command=)
  /bin/rm -f "${STATE_DIR}/app.pid" "${STATE_DIR}/server.state" \
    "${STATE_DIR}/server.pid" "${STATE_DIR}/server.instance"
}

stop_existing_installation

echo "Building Odin..."
( cd "${REPO}" && "${NPM}" install && "${NPM}" run build )

mkdir -p "${STATE_DIR}" "${LOG_DIR}"
chmod 700 "${STATE_DIR}" "${LOG_DIR}"

TMP="$(mktemp -d)"

cat > "${TMP}/odin.applescript" <<APPLESCRIPT
property dashboardURL : "http://127.0.0.1:${PORT}"
property isQuitting : false
property isEnsuring : false

on runLauncher(commandName)
  set launcherPath to POSIX path of (path to resource "odin-launcher.sh")
  do shell script "/bin/bash " & quoted form of launcherPath & " " & quoted form of commandName
end runLauncher

on registerApp()
  set launcherPath to POSIX path of (path to resource "odin-launcher.sh")
  do shell script "/bin/bash " & quoted form of launcherPath & " register-app \"\$PPID\""
end registerApp

on ensureServer(showFailure)
  if isEnsuring then return false
  set isEnsuring to true
  try
    my runLauncher("ensure")
    set isEnsuring to false
    return true
  on error errorMessage
    set isEnsuring to false
    if showFailure then display alert "Odin could not start" message errorMessage as critical
    return false
  end try
end ensureServer

on openDashboard(showFailure)
  if my ensureServer(showFailure) then open location dashboardURL
end openDashboard

on run
  try
    my registerApp()
  end try
  my openDashboard(true)
end run

on reopen
  try
    my registerApp()
  end try
  my openDashboard(true)
end reopen

on idle
  if not isQuitting then my ensureServer(false)
  return 10
end idle

on quit
  set isQuitting to true
  try
    my runLauncher("stop")
  end try
  try
    my runLauncher("unregister-app")
  end try
  continue quit
end quit
APPLESCRIPT

{
  printf '#!/usr/bin/env bash\n'
  printf 'set -uo pipefail\n\n'
  printf 'REPO=%q\n' "${REPO}"
  printf 'SERVER=%q\n' "${REPO}/server/dist/index.js"
  printf 'APP=%q\n' "${APP}"
  printf 'STATE_DIR=%q\n' "${STATE_DIR}"
  printf 'LOG_DIR=%q\n' "${LOG_DIR}"
  printf 'PORT=%q\n' "${PORT}"
  printf 'NODE=%q\n' "${NODE}"
  printf 'CURL=%q\n' "${CURL}"
  printf 'LSOF=%q\n' "${LSOF}"
  printf 'NOHUP=%q\n' "${NOHUP}"
  printf 'PS=%q\n' "${PS}"
  printf 'CLAUDE=%q\n' "${CLAUDE}"
  cat <<'LAUNCHER'

SERVER_STATE_FILE="${STATE_DIR}/server.state"
APP_PID_FILE="${STATE_DIR}/app.pid"
LOG_FILE="${LOG_DIR}/odin.log"
LOCK_DIR="${STATE_DIR}/launcher.lock"

umask 077
/bin/mkdir -p "${STATE_DIR}" "${LOG_DIR}" || exit 1
/bin/chmod 700 "${STATE_DIR}" "${LOG_DIR}" || exit 1

process_command() {
  "${PS}" -ww -p "$1" -o command= 2>/dev/null
}

read_server_state() {
  OWNED_PID=""
  INSTANCE=""
  [[ -r "${SERVER_STATE_FILE}" ]] || return 1
  read -r OWNED_PID INSTANCE < "${SERVER_STATE_FILE}" || return 1
  [[ "${OWNED_PID}" =~ ^[0-9]+$ && "${INSTANCE}" =~ ^[0-9]+-[0-9]+-[0-9]+$ ]]
}

clear_server_state() {
  /bin/rm -f "${SERVER_STATE_FILE}" "${STATE_DIR}/server.pid" "${STATE_DIR}/server.instance"
}

is_owned_process() {
  local pid="$1"
  local instance="$2"
  local command
  kill -0 "${pid}" 2>/dev/null || return 1
  command="$(process_command "${pid}")" || return 1
  [[ "${command}" == *"${NODE} ${SERVER} --odin-launcher-instance=${instance}" ]]
}

listener_is_pid() {
  local expected_pid="$1"
  local listener
  local listeners
  listeners="$("${LSOF}" -nP -a -p "${expected_pid}" -iTCP:"${PORT}" -sTCP:LISTEN -t 2>/dev/null)" || return 1
  for listener in ${listeners}; do
    [[ "${listener}" == "${expected_pid}" ]] && return 0
  done
  return 1
}

port_has_listener() {
  [[ -n "$("${LSOF}" -nP -iTCP:"${PORT}" -sTCP:LISTEN -t 2>/dev/null)" ]]
}

health_is_odin() {
  local expected_instance="${1:-}"
  local body
  body="$("${CURL}" --fail --silent --show-error --connect-timeout 1 --max-time 1 \
    "http://127.0.0.1:${PORT}/api/health" 2>/dev/null)" || return 1
  "${NODE}" -e '
    try {
      const health = JSON.parse(process.argv[1]);
      const port = Number(process.argv[2]);
      const expected = process.argv[3];
      const expectedRoot = process.argv[4];
      const instanceMatches = !expected || health.instanceId === expected;
      const checkoutMatches = health.checkoutRoot === expectedRoot;
      process.exit(health.ok === true && health.service === "odin" && health.port === port && instanceMatches && checkoutMatches ? 0 : 1);
    } catch {
      process.exit(1);
    }
  ' "${body}" "${PORT}" "${expected_instance}" "${REPO}" >/dev/null 2>&1
}

owned_server_is_ready() {
  local pid="$1"
  local instance="$2"
  is_owned_process "${pid}" "${instance}" && listener_is_pid "${pid}" && health_is_odin "${instance}"
}

stop_owned_server() {
  local i
  if ! read_server_state; then
    clear_server_state
    return 0
  fi
  if ! is_owned_process "${OWNED_PID}" "${INSTANCE}"; then
    clear_server_state
    return 0
  fi

  kill -TERM "${OWNED_PID}" 2>/dev/null || true
  for i in {1..80}; do
    is_owned_process "${OWNED_PID}" "${INSTANCE}" || break
    /bin/sleep 0.1
  done
  if is_owned_process "${OWNED_PID}" "${INSTANCE}"; then
    kill -KILL "${OWNED_PID}" 2>/dev/null || true
  fi
  clear_server_state
}

write_server_state() {
  local pid="$1"
  local instance="$2"
  printf '%s %s\n' "${pid}" "${instance}" > "${SERVER_STATE_FILE}.$$" || return 1
  /bin/mv -f "${SERVER_STATE_FILE}.$$" "${SERVER_STATE_FILE}"
}

start_owned_server() {
  local i
  local instance="$$-${RANDOM}-${RANDOM}"
  local pid

  (
    cd "${REPO}" || exit 1
    export HELM_PORT="${PORT}"
    export ODIN_LAUNCHER_INSTANCE="${instance}"
    export ODIN_INSTANCE_ID="${instance}"
    [[ -n "${CLAUDE}" ]] && export ODIN_CLAUDE_BIN="${CLAUDE}"
    exec "${NOHUP}" "${NODE}" "${SERVER}" "--odin-launcher-instance=${instance}"
  ) >> "${LOG_FILE}" 2>&1 </dev/null &
  pid=$!
  if ! write_server_state "${pid}" "${instance}"; then
    kill -TERM "${pid}" 2>/dev/null || true
    return 1
  fi

  for i in {1..20}; do
    /bin/sleep 0.5
    if owned_server_is_ready "${pid}" "${instance}"; then
      return 0
    fi
    kill -0 "${pid}" 2>/dev/null || break
  done

  stop_owned_server
  printf '[launcher] Odin did not become healthy on port %s.\n' "${PORT}" >> "${LOG_FILE}"
  printf 'Odin did not become healthy on port %s. See %s.\n' "${PORT}" "${LOG_FILE}" >&2
  return 1
}

ensure_server() {
  local i
  if read_server_state && is_owned_process "${OWNED_PID}" "${INSTANCE}"; then
    # Another run/reopen/idle event may arrive while the first app event is
    # still starting this owned server. Join that startup instead of killing it.
    for i in {1..20}; do
      if owned_server_is_ready "${OWNED_PID}" "${INSTANCE}"; then
        return 0
      fi
      /bin/sleep 0.5
    done
    stop_owned_server
  else
    clear_server_state
  fi

  # A manually started healthy Odin server (including `npm run dev`) is usable
  # but remains unowned, so quitting the Dock app will never terminate it.
  if health_is_odin ""; then
    return 0
  fi
  if port_has_listener; then
    printf '[launcher] Port %s is already used by another process.\n' "${PORT}" >> "${LOG_FILE}"
    printf 'Port %s is already used by another process.\n' "${PORT}" >&2
    return 1
  fi

  start_owned_server
}

is_app_process() {
  local command
  command="$(process_command "$1")" || return 1
  [[ "${command}" == *"${APP}/Contents/MacOS/applet"* ]]
}

release_lock() {
  local owner=""
  [[ -r "${LOCK_DIR}/owner" ]] && IFS= read -r owner < "${LOCK_DIR}/owner"
  if [[ "${owner}" == "${LOCK_OWNER}" ]]; then
    /bin/rm -rf "${LOCK_DIR}"
  fi
}

acquire_lock() {
  local i owner="" owner_pid="" current_owner="" stale=""
  LOCK_OWNER="$$-${RANDOM}-${RANDOM}"
  for i in {1..150}; do
    if /bin/mkdir "${LOCK_DIR}" 2>/dev/null; then
      printf '%s\n' "${LOCK_OWNER}" > "${LOCK_DIR}/owner"
      trap release_lock EXIT
      return 0
    fi
    if [[ -r "${LOCK_DIR}/owner" ]]; then
      IFS= read -r owner < "${LOCK_DIR}/owner" || owner=""
    else
      /bin/sleep 0.1
      [[ -r "${LOCK_DIR}/owner" ]] && IFS= read -r owner < "${LOCK_DIR}/owner"
    fi
    owner_pid="${owner%%-*}"
    if [[ ! "${owner}" =~ ^[0-9]+-[0-9]+-[0-9]+$ ]] || ! kill -0 "${owner_pid}" 2>/dev/null; then
      current_owner=""
      [[ -r "${LOCK_DIR}/owner" ]] && IFS= read -r current_owner < "${LOCK_DIR}/owner"
      [[ "${current_owner}" == "${owner}" ]] || continue
      stale="${LOCK_DIR}.stale.${LOCK_OWNER}"
      if /bin/mv "${LOCK_DIR}" "${stale}" 2>/dev/null; then
        /bin/rm -rf "${stale}"
      fi
      continue
    fi
    /bin/sleep 0.1
  done
  printf 'Another Odin launcher operation is still running.\n' >&2
  return 1
}

acquire_lock || exit 1

register_app() {
  local pid="${1:-}"
  [[ "${pid}" =~ ^[0-9]+$ ]] || return 1
  is_app_process "${pid}" || return 1
  printf '%s\n' "${pid}" > "${APP_PID_FILE}"
}

case "${1:-}" in
  ensure)
    ensure_server
    ;;
  stop)
    stop_owned_server
    ;;
  register-app)
    register_app "${2:-}"
    ;;
  unregister-app)
    /bin/rm -f "${APP_PID_FILE}"
    ;;
  *)
    printf 'Unknown Odin launcher command.\n' >&2
    exit 2
    ;;
esac
LAUNCHER
} > "${TMP}/odin-launcher.sh"

echo "Creating ${APP} ..."
"${OSACOMPILE}" -s -o "${TMP}/Odin.app" "${TMP}/odin.applescript"
/bin/cp "${TMP}/odin-launcher.sh" "${TMP}/Odin.app/Contents/Resources/odin-launcher.sh"
/bin/chmod 700 "${TMP}/Odin.app/Contents/Resources/odin-launcher.sh"
printf '%s\n' "${APP_MARKER}" > "${TMP}/Odin.app/Contents/Resources/odin-app.marker"
/bin/chmod 600 "${TMP}/Odin.app/Contents/Resources/odin-app.marker"
"${CODESIGN}" --force --sign - "${TMP}/Odin.app" >/dev/null
if [[ -e "${APP}" || -L "${APP}" ]]; then
  echo "${APP} appeared during installation; the previous Odin app remains at ${BACKUP_APP}." >&2
  exit 1
fi
/bin/mv "${TMP}/Odin.app" "${APP}"
if [[ -n "${BACKUP_APP}" ]]; then
  /bin/rm -rf "${BACKUP_APP}"
  BACKUP_APP=""
fi

echo "Done. Open 'Odin' from Applications (drag it to your Dock to pin it)."
echo "Server state: ${STATE_DIR}"
echo "Server logs: ${LOG_DIR}/odin.log"
